spring.application.name=Zipkin_UserService

server.port=8082

# The full URL to the Zipkin API endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Trace sampling probability (1.0 = trace 100% of requests. Lower this in production, e.g., 0.1 for 10%)
management.tracing.sampling.probability=1.0
